[package]
name = "qsh"
version = "0.1.0"
edition = "2021"

[dependencies]
dynasmrt = "*"
iced-x86 = { optional = true, version = "*" }
bitflags = "*"

[features]
default = ["iced", "catch_unwind"]
iced = ["iced-x86"]
catch_unwind = []
